# /* **************************************************************************
#  *                                                                          *
#  *     (C) Copyright Paul Mensonides 2002.
#  *     Distributed under the Boost Software License, Version 1.0. (See
#  *     accompanying file LICENSE_1_0.txt or copy at
#  *     http://www.boost.org/LICENSE_1_0.txt)
#  *                                                                          *
#  ************************************************************************** */
#
# /* Revised by Edward Diener (2020) */
#
# /* See http://www.boost.org for most recent version. */
#
# ifndef NSL_PREPROCESSOR_SEQ_ELEM_H
# define NSL_PREPROCESSOR_SEQ_ELEM_H
#
# include "nsl/preprocessor/cat.h"
# include "nsl/preprocessor/config/config.h"
# include "nsl/preprocessor/facilities/empty.h"
#
# /* NSL_PP_SEQ_ELEM */
#
# if ~NSL_PP_CONFIG_FLAGS() & NSL_PP_CONFIG_MWCC()
#    define NSL_PP_SEQ_ELEM(i, seq) NSL_PP_SEQ_ELEM_I(i, seq)
# else
#    define NSL_PP_SEQ_ELEM(i, seq) NSL_PP_SEQ_ELEM_I((i, seq))
# endif
#
# if NSL_PP_CONFIG_FLAGS() & NSL_PP_CONFIG_MSVC()
#    define NSL_PP_SEQ_ELEM_I(i, seq) NSL_PP_SEQ_ELEM_II((NSL_PP_SEQ_ELEM_ ## i seq))
#    define NSL_PP_SEQ_ELEM_II(res) NSL_PP_SEQ_ELEM_IV(NSL_PP_SEQ_ELEM_III res)
#    define NSL_PP_SEQ_ELEM_III(x, _) x NSL_PP_EMPTY()
#    define NSL_PP_SEQ_ELEM_IV(x) x
# elif NSL_PP_CONFIG_FLAGS() & NSL_PP_CONFIG_MWCC()
#    define NSL_PP_SEQ_ELEM_I(par) NSL_PP_SEQ_ELEM_II ## par
#    define NSL_PP_SEQ_ELEM_II(i, seq) NSL_PP_SEQ_ELEM_III(NSL_PP_SEQ_ELEM_ ## i ## seq)
#    define NSL_PP_SEQ_ELEM_III(im) NSL_PP_SEQ_ELEM_IV(im)
#    define NSL_PP_SEQ_ELEM_IV(x, _) x
# else
#    if defined(__IBMC__) || defined(__IBMCPP__)
#        define NSL_PP_SEQ_ELEM_I(i, seq) NSL_PP_SEQ_ELEM_II(NSL_PP_CAT(NSL_PP_SEQ_ELEM_ ## i, seq))
#    else
#        define NSL_PP_SEQ_ELEM_I(i, seq) NSL_PP_SEQ_ELEM_II(NSL_PP_SEQ_ELEM_ ## i seq)
#    endif
#    define NSL_PP_SEQ_ELEM_II(im) NSL_PP_SEQ_ELEM_III(im)
#    define NSL_PP_SEQ_ELEM_III(x, _) x
# endif
#
# if ~NSL_PP_CONFIG_FLAGS() & NSL_PP_CONFIG_STRICT()
#
# define NSL_PP_SEQ_ELEM_0(x) x, NSL_PP_NIL
# define NSL_PP_SEQ_ELEM_1(_) NSL_PP_SEQ_ELEM_0
# define NSL_PP_SEQ_ELEM_2(_) NSL_PP_SEQ_ELEM_1
# define NSL_PP_SEQ_ELEM_3(_) NSL_PP_SEQ_ELEM_2
# define NSL_PP_SEQ_ELEM_4(_) NSL_PP_SEQ_ELEM_3
# define NSL_PP_SEQ_ELEM_5(_) NSL_PP_SEQ_ELEM_4
# define NSL_PP_SEQ_ELEM_6(_) NSL_PP_SEQ_ELEM_5
# define NSL_PP_SEQ_ELEM_7(_) NSL_PP_SEQ_ELEM_6
# define NSL_PP_SEQ_ELEM_8(_) NSL_PP_SEQ_ELEM_7
# define NSL_PP_SEQ_ELEM_9(_) NSL_PP_SEQ_ELEM_8
# define NSL_PP_SEQ_ELEM_10(_) NSL_PP_SEQ_ELEM_9
# define NSL_PP_SEQ_ELEM_11(_) NSL_PP_SEQ_ELEM_10
# define NSL_PP_SEQ_ELEM_12(_) NSL_PP_SEQ_ELEM_11
# define NSL_PP_SEQ_ELEM_13(_) NSL_PP_SEQ_ELEM_12
# define NSL_PP_SEQ_ELEM_14(_) NSL_PP_SEQ_ELEM_13
# define NSL_PP_SEQ_ELEM_15(_) NSL_PP_SEQ_ELEM_14
# define NSL_PP_SEQ_ELEM_16(_) NSL_PP_SEQ_ELEM_15
# define NSL_PP_SEQ_ELEM_17(_) NSL_PP_SEQ_ELEM_16
# define NSL_PP_SEQ_ELEM_18(_) NSL_PP_SEQ_ELEM_17
# define NSL_PP_SEQ_ELEM_19(_) NSL_PP_SEQ_ELEM_18
# define NSL_PP_SEQ_ELEM_20(_) NSL_PP_SEQ_ELEM_19
# define NSL_PP_SEQ_ELEM_21(_) NSL_PP_SEQ_ELEM_20
# define NSL_PP_SEQ_ELEM_22(_) NSL_PP_SEQ_ELEM_21
# define NSL_PP_SEQ_ELEM_23(_) NSL_PP_SEQ_ELEM_22
# define NSL_PP_SEQ_ELEM_24(_) NSL_PP_SEQ_ELEM_23
# define NSL_PP_SEQ_ELEM_25(_) NSL_PP_SEQ_ELEM_24
# define NSL_PP_SEQ_ELEM_26(_) NSL_PP_SEQ_ELEM_25
# define NSL_PP_SEQ_ELEM_27(_) NSL_PP_SEQ_ELEM_26
# define NSL_PP_SEQ_ELEM_28(_) NSL_PP_SEQ_ELEM_27
# define NSL_PP_SEQ_ELEM_29(_) NSL_PP_SEQ_ELEM_28
# define NSL_PP_SEQ_ELEM_30(_) NSL_PP_SEQ_ELEM_29
# define NSL_PP_SEQ_ELEM_31(_) NSL_PP_SEQ_ELEM_30
# define NSL_PP_SEQ_ELEM_32(_) NSL_PP_SEQ_ELEM_31
# define NSL_PP_SEQ_ELEM_33(_) NSL_PP_SEQ_ELEM_32
# define NSL_PP_SEQ_ELEM_34(_) NSL_PP_SEQ_ELEM_33
# define NSL_PP_SEQ_ELEM_35(_) NSL_PP_SEQ_ELEM_34
# define NSL_PP_SEQ_ELEM_36(_) NSL_PP_SEQ_ELEM_35
# define NSL_PP_SEQ_ELEM_37(_) NSL_PP_SEQ_ELEM_36
# define NSL_PP_SEQ_ELEM_38(_) NSL_PP_SEQ_ELEM_37
# define NSL_PP_SEQ_ELEM_39(_) NSL_PP_SEQ_ELEM_38
# define NSL_PP_SEQ_ELEM_40(_) NSL_PP_SEQ_ELEM_39
# define NSL_PP_SEQ_ELEM_41(_) NSL_PP_SEQ_ELEM_40
# define NSL_PP_SEQ_ELEM_42(_) NSL_PP_SEQ_ELEM_41
# define NSL_PP_SEQ_ELEM_43(_) NSL_PP_SEQ_ELEM_42
# define NSL_PP_SEQ_ELEM_44(_) NSL_PP_SEQ_ELEM_43
# define NSL_PP_SEQ_ELEM_45(_) NSL_PP_SEQ_ELEM_44
# define NSL_PP_SEQ_ELEM_46(_) NSL_PP_SEQ_ELEM_45
# define NSL_PP_SEQ_ELEM_47(_) NSL_PP_SEQ_ELEM_46
# define NSL_PP_SEQ_ELEM_48(_) NSL_PP_SEQ_ELEM_47
# define NSL_PP_SEQ_ELEM_49(_) NSL_PP_SEQ_ELEM_48
# define NSL_PP_SEQ_ELEM_50(_) NSL_PP_SEQ_ELEM_49
# define NSL_PP_SEQ_ELEM_51(_) NSL_PP_SEQ_ELEM_50
# define NSL_PP_SEQ_ELEM_52(_) NSL_PP_SEQ_ELEM_51
# define NSL_PP_SEQ_ELEM_53(_) NSL_PP_SEQ_ELEM_52
# define NSL_PP_SEQ_ELEM_54(_) NSL_PP_SEQ_ELEM_53
# define NSL_PP_SEQ_ELEM_55(_) NSL_PP_SEQ_ELEM_54
# define NSL_PP_SEQ_ELEM_56(_) NSL_PP_SEQ_ELEM_55
# define NSL_PP_SEQ_ELEM_57(_) NSL_PP_SEQ_ELEM_56
# define NSL_PP_SEQ_ELEM_58(_) NSL_PP_SEQ_ELEM_57
# define NSL_PP_SEQ_ELEM_59(_) NSL_PP_SEQ_ELEM_58
# define NSL_PP_SEQ_ELEM_60(_) NSL_PP_SEQ_ELEM_59
# define NSL_PP_SEQ_ELEM_61(_) NSL_PP_SEQ_ELEM_60
# define NSL_PP_SEQ_ELEM_62(_) NSL_PP_SEQ_ELEM_61
# define NSL_PP_SEQ_ELEM_63(_) NSL_PP_SEQ_ELEM_62
# define NSL_PP_SEQ_ELEM_64(_) NSL_PP_SEQ_ELEM_63
# define NSL_PP_SEQ_ELEM_65(_) NSL_PP_SEQ_ELEM_64
# define NSL_PP_SEQ_ELEM_66(_) NSL_PP_SEQ_ELEM_65
# define NSL_PP_SEQ_ELEM_67(_) NSL_PP_SEQ_ELEM_66
# define NSL_PP_SEQ_ELEM_68(_) NSL_PP_SEQ_ELEM_67
# define NSL_PP_SEQ_ELEM_69(_) NSL_PP_SEQ_ELEM_68
# define NSL_PP_SEQ_ELEM_70(_) NSL_PP_SEQ_ELEM_69
# define NSL_PP_SEQ_ELEM_71(_) NSL_PP_SEQ_ELEM_70
# define NSL_PP_SEQ_ELEM_72(_) NSL_PP_SEQ_ELEM_71
# define NSL_PP_SEQ_ELEM_73(_) NSL_PP_SEQ_ELEM_72
# define NSL_PP_SEQ_ELEM_74(_) NSL_PP_SEQ_ELEM_73
# define NSL_PP_SEQ_ELEM_75(_) NSL_PP_SEQ_ELEM_74
# define NSL_PP_SEQ_ELEM_76(_) NSL_PP_SEQ_ELEM_75
# define NSL_PP_SEQ_ELEM_77(_) NSL_PP_SEQ_ELEM_76
# define NSL_PP_SEQ_ELEM_78(_) NSL_PP_SEQ_ELEM_77
# define NSL_PP_SEQ_ELEM_79(_) NSL_PP_SEQ_ELEM_78
# define NSL_PP_SEQ_ELEM_80(_) NSL_PP_SEQ_ELEM_79
# define NSL_PP_SEQ_ELEM_81(_) NSL_PP_SEQ_ELEM_80
# define NSL_PP_SEQ_ELEM_82(_) NSL_PP_SEQ_ELEM_81
# define NSL_PP_SEQ_ELEM_83(_) NSL_PP_SEQ_ELEM_82
# define NSL_PP_SEQ_ELEM_84(_) NSL_PP_SEQ_ELEM_83
# define NSL_PP_SEQ_ELEM_85(_) NSL_PP_SEQ_ELEM_84
# define NSL_PP_SEQ_ELEM_86(_) NSL_PP_SEQ_ELEM_85
# define NSL_PP_SEQ_ELEM_87(_) NSL_PP_SEQ_ELEM_86
# define NSL_PP_SEQ_ELEM_88(_) NSL_PP_SEQ_ELEM_87
# define NSL_PP_SEQ_ELEM_89(_) NSL_PP_SEQ_ELEM_88
# define NSL_PP_SEQ_ELEM_90(_) NSL_PP_SEQ_ELEM_89
# define NSL_PP_SEQ_ELEM_91(_) NSL_PP_SEQ_ELEM_90
# define NSL_PP_SEQ_ELEM_92(_) NSL_PP_SEQ_ELEM_91
# define NSL_PP_SEQ_ELEM_93(_) NSL_PP_SEQ_ELEM_92
# define NSL_PP_SEQ_ELEM_94(_) NSL_PP_SEQ_ELEM_93
# define NSL_PP_SEQ_ELEM_95(_) NSL_PP_SEQ_ELEM_94
# define NSL_PP_SEQ_ELEM_96(_) NSL_PP_SEQ_ELEM_95
# define NSL_PP_SEQ_ELEM_97(_) NSL_PP_SEQ_ELEM_96
# define NSL_PP_SEQ_ELEM_98(_) NSL_PP_SEQ_ELEM_97
# define NSL_PP_SEQ_ELEM_99(_) NSL_PP_SEQ_ELEM_98
# define NSL_PP_SEQ_ELEM_100(_) NSL_PP_SEQ_ELEM_99
# define NSL_PP_SEQ_ELEM_101(_) NSL_PP_SEQ_ELEM_100
# define NSL_PP_SEQ_ELEM_102(_) NSL_PP_SEQ_ELEM_101
# define NSL_PP_SEQ_ELEM_103(_) NSL_PP_SEQ_ELEM_102
# define NSL_PP_SEQ_ELEM_104(_) NSL_PP_SEQ_ELEM_103
# define NSL_PP_SEQ_ELEM_105(_) NSL_PP_SEQ_ELEM_104
# define NSL_PP_SEQ_ELEM_106(_) NSL_PP_SEQ_ELEM_105
# define NSL_PP_SEQ_ELEM_107(_) NSL_PP_SEQ_ELEM_106
# define NSL_PP_SEQ_ELEM_108(_) NSL_PP_SEQ_ELEM_107
# define NSL_PP_SEQ_ELEM_109(_) NSL_PP_SEQ_ELEM_108
# define NSL_PP_SEQ_ELEM_110(_) NSL_PP_SEQ_ELEM_109
# define NSL_PP_SEQ_ELEM_111(_) NSL_PP_SEQ_ELEM_110
# define NSL_PP_SEQ_ELEM_112(_) NSL_PP_SEQ_ELEM_111
# define NSL_PP_SEQ_ELEM_113(_) NSL_PP_SEQ_ELEM_112
# define NSL_PP_SEQ_ELEM_114(_) NSL_PP_SEQ_ELEM_113
# define NSL_PP_SEQ_ELEM_115(_) NSL_PP_SEQ_ELEM_114
# define NSL_PP_SEQ_ELEM_116(_) NSL_PP_SEQ_ELEM_115
# define NSL_PP_SEQ_ELEM_117(_) NSL_PP_SEQ_ELEM_116
# define NSL_PP_SEQ_ELEM_118(_) NSL_PP_SEQ_ELEM_117
# define NSL_PP_SEQ_ELEM_119(_) NSL_PP_SEQ_ELEM_118
# define NSL_PP_SEQ_ELEM_120(_) NSL_PP_SEQ_ELEM_119
# define NSL_PP_SEQ_ELEM_121(_) NSL_PP_SEQ_ELEM_120
# define NSL_PP_SEQ_ELEM_122(_) NSL_PP_SEQ_ELEM_121
# define NSL_PP_SEQ_ELEM_123(_) NSL_PP_SEQ_ELEM_122
# define NSL_PP_SEQ_ELEM_124(_) NSL_PP_SEQ_ELEM_123
# define NSL_PP_SEQ_ELEM_125(_) NSL_PP_SEQ_ELEM_124
# define NSL_PP_SEQ_ELEM_126(_) NSL_PP_SEQ_ELEM_125
# define NSL_PP_SEQ_ELEM_127(_) NSL_PP_SEQ_ELEM_126
# define NSL_PP_SEQ_ELEM_128(_) NSL_PP_SEQ_ELEM_127
# define NSL_PP_SEQ_ELEM_129(_) NSL_PP_SEQ_ELEM_128
# define NSL_PP_SEQ_ELEM_130(_) NSL_PP_SEQ_ELEM_129
# define NSL_PP_SEQ_ELEM_131(_) NSL_PP_SEQ_ELEM_130
# define NSL_PP_SEQ_ELEM_132(_) NSL_PP_SEQ_ELEM_131
# define NSL_PP_SEQ_ELEM_133(_) NSL_PP_SEQ_ELEM_132
# define NSL_PP_SEQ_ELEM_134(_) NSL_PP_SEQ_ELEM_133
# define NSL_PP_SEQ_ELEM_135(_) NSL_PP_SEQ_ELEM_134
# define NSL_PP_SEQ_ELEM_136(_) NSL_PP_SEQ_ELEM_135
# define NSL_PP_SEQ_ELEM_137(_) NSL_PP_SEQ_ELEM_136
# define NSL_PP_SEQ_ELEM_138(_) NSL_PP_SEQ_ELEM_137
# define NSL_PP_SEQ_ELEM_139(_) NSL_PP_SEQ_ELEM_138
# define NSL_PP_SEQ_ELEM_140(_) NSL_PP_SEQ_ELEM_139
# define NSL_PP_SEQ_ELEM_141(_) NSL_PP_SEQ_ELEM_140
# define NSL_PP_SEQ_ELEM_142(_) NSL_PP_SEQ_ELEM_141
# define NSL_PP_SEQ_ELEM_143(_) NSL_PP_SEQ_ELEM_142
# define NSL_PP_SEQ_ELEM_144(_) NSL_PP_SEQ_ELEM_143
# define NSL_PP_SEQ_ELEM_145(_) NSL_PP_SEQ_ELEM_144
# define NSL_PP_SEQ_ELEM_146(_) NSL_PP_SEQ_ELEM_145
# define NSL_PP_SEQ_ELEM_147(_) NSL_PP_SEQ_ELEM_146
# define NSL_PP_SEQ_ELEM_148(_) NSL_PP_SEQ_ELEM_147
# define NSL_PP_SEQ_ELEM_149(_) NSL_PP_SEQ_ELEM_148
# define NSL_PP_SEQ_ELEM_150(_) NSL_PP_SEQ_ELEM_149
# define NSL_PP_SEQ_ELEM_151(_) NSL_PP_SEQ_ELEM_150
# define NSL_PP_SEQ_ELEM_152(_) NSL_PP_SEQ_ELEM_151
# define NSL_PP_SEQ_ELEM_153(_) NSL_PP_SEQ_ELEM_152
# define NSL_PP_SEQ_ELEM_154(_) NSL_PP_SEQ_ELEM_153
# define NSL_PP_SEQ_ELEM_155(_) NSL_PP_SEQ_ELEM_154
# define NSL_PP_SEQ_ELEM_156(_) NSL_PP_SEQ_ELEM_155
# define NSL_PP_SEQ_ELEM_157(_) NSL_PP_SEQ_ELEM_156
# define NSL_PP_SEQ_ELEM_158(_) NSL_PP_SEQ_ELEM_157
# define NSL_PP_SEQ_ELEM_159(_) NSL_PP_SEQ_ELEM_158
# define NSL_PP_SEQ_ELEM_160(_) NSL_PP_SEQ_ELEM_159
# define NSL_PP_SEQ_ELEM_161(_) NSL_PP_SEQ_ELEM_160
# define NSL_PP_SEQ_ELEM_162(_) NSL_PP_SEQ_ELEM_161
# define NSL_PP_SEQ_ELEM_163(_) NSL_PP_SEQ_ELEM_162
# define NSL_PP_SEQ_ELEM_164(_) NSL_PP_SEQ_ELEM_163
# define NSL_PP_SEQ_ELEM_165(_) NSL_PP_SEQ_ELEM_164
# define NSL_PP_SEQ_ELEM_166(_) NSL_PP_SEQ_ELEM_165
# define NSL_PP_SEQ_ELEM_167(_) NSL_PP_SEQ_ELEM_166
# define NSL_PP_SEQ_ELEM_168(_) NSL_PP_SEQ_ELEM_167
# define NSL_PP_SEQ_ELEM_169(_) NSL_PP_SEQ_ELEM_168
# define NSL_PP_SEQ_ELEM_170(_) NSL_PP_SEQ_ELEM_169
# define NSL_PP_SEQ_ELEM_171(_) NSL_PP_SEQ_ELEM_170
# define NSL_PP_SEQ_ELEM_172(_) NSL_PP_SEQ_ELEM_171
# define NSL_PP_SEQ_ELEM_173(_) NSL_PP_SEQ_ELEM_172
# define NSL_PP_SEQ_ELEM_174(_) NSL_PP_SEQ_ELEM_173
# define NSL_PP_SEQ_ELEM_175(_) NSL_PP_SEQ_ELEM_174
# define NSL_PP_SEQ_ELEM_176(_) NSL_PP_SEQ_ELEM_175
# define NSL_PP_SEQ_ELEM_177(_) NSL_PP_SEQ_ELEM_176
# define NSL_PP_SEQ_ELEM_178(_) NSL_PP_SEQ_ELEM_177
# define NSL_PP_SEQ_ELEM_179(_) NSL_PP_SEQ_ELEM_178
# define NSL_PP_SEQ_ELEM_180(_) NSL_PP_SEQ_ELEM_179
# define NSL_PP_SEQ_ELEM_181(_) NSL_PP_SEQ_ELEM_180
# define NSL_PP_SEQ_ELEM_182(_) NSL_PP_SEQ_ELEM_181
# define NSL_PP_SEQ_ELEM_183(_) NSL_PP_SEQ_ELEM_182
# define NSL_PP_SEQ_ELEM_184(_) NSL_PP_SEQ_ELEM_183
# define NSL_PP_SEQ_ELEM_185(_) NSL_PP_SEQ_ELEM_184
# define NSL_PP_SEQ_ELEM_186(_) NSL_PP_SEQ_ELEM_185
# define NSL_PP_SEQ_ELEM_187(_) NSL_PP_SEQ_ELEM_186
# define NSL_PP_SEQ_ELEM_188(_) NSL_PP_SEQ_ELEM_187
# define NSL_PP_SEQ_ELEM_189(_) NSL_PP_SEQ_ELEM_188
# define NSL_PP_SEQ_ELEM_190(_) NSL_PP_SEQ_ELEM_189
# define NSL_PP_SEQ_ELEM_191(_) NSL_PP_SEQ_ELEM_190
# define NSL_PP_SEQ_ELEM_192(_) NSL_PP_SEQ_ELEM_191
# define NSL_PP_SEQ_ELEM_193(_) NSL_PP_SEQ_ELEM_192
# define NSL_PP_SEQ_ELEM_194(_) NSL_PP_SEQ_ELEM_193
# define NSL_PP_SEQ_ELEM_195(_) NSL_PP_SEQ_ELEM_194
# define NSL_PP_SEQ_ELEM_196(_) NSL_PP_SEQ_ELEM_195
# define NSL_PP_SEQ_ELEM_197(_) NSL_PP_SEQ_ELEM_196
# define NSL_PP_SEQ_ELEM_198(_) NSL_PP_SEQ_ELEM_197
# define NSL_PP_SEQ_ELEM_199(_) NSL_PP_SEQ_ELEM_198
# define NSL_PP_SEQ_ELEM_200(_) NSL_PP_SEQ_ELEM_199
# define NSL_PP_SEQ_ELEM_201(_) NSL_PP_SEQ_ELEM_200
# define NSL_PP_SEQ_ELEM_202(_) NSL_PP_SEQ_ELEM_201
# define NSL_PP_SEQ_ELEM_203(_) NSL_PP_SEQ_ELEM_202
# define NSL_PP_SEQ_ELEM_204(_) NSL_PP_SEQ_ELEM_203
# define NSL_PP_SEQ_ELEM_205(_) NSL_PP_SEQ_ELEM_204
# define NSL_PP_SEQ_ELEM_206(_) NSL_PP_SEQ_ELEM_205
# define NSL_PP_SEQ_ELEM_207(_) NSL_PP_SEQ_ELEM_206
# define NSL_PP_SEQ_ELEM_208(_) NSL_PP_SEQ_ELEM_207
# define NSL_PP_SEQ_ELEM_209(_) NSL_PP_SEQ_ELEM_208
# define NSL_PP_SEQ_ELEM_210(_) NSL_PP_SEQ_ELEM_209
# define NSL_PP_SEQ_ELEM_211(_) NSL_PP_SEQ_ELEM_210
# define NSL_PP_SEQ_ELEM_212(_) NSL_PP_SEQ_ELEM_211
# define NSL_PP_SEQ_ELEM_213(_) NSL_PP_SEQ_ELEM_212
# define NSL_PP_SEQ_ELEM_214(_) NSL_PP_SEQ_ELEM_213
# define NSL_PP_SEQ_ELEM_215(_) NSL_PP_SEQ_ELEM_214
# define NSL_PP_SEQ_ELEM_216(_) NSL_PP_SEQ_ELEM_215
# define NSL_PP_SEQ_ELEM_217(_) NSL_PP_SEQ_ELEM_216
# define NSL_PP_SEQ_ELEM_218(_) NSL_PP_SEQ_ELEM_217
# define NSL_PP_SEQ_ELEM_219(_) NSL_PP_SEQ_ELEM_218
# define NSL_PP_SEQ_ELEM_220(_) NSL_PP_SEQ_ELEM_219
# define NSL_PP_SEQ_ELEM_221(_) NSL_PP_SEQ_ELEM_220
# define NSL_PP_SEQ_ELEM_222(_) NSL_PP_SEQ_ELEM_221
# define NSL_PP_SEQ_ELEM_223(_) NSL_PP_SEQ_ELEM_222
# define NSL_PP_SEQ_ELEM_224(_) NSL_PP_SEQ_ELEM_223
# define NSL_PP_SEQ_ELEM_225(_) NSL_PP_SEQ_ELEM_224
# define NSL_PP_SEQ_ELEM_226(_) NSL_PP_SEQ_ELEM_225
# define NSL_PP_SEQ_ELEM_227(_) NSL_PP_SEQ_ELEM_226
# define NSL_PP_SEQ_ELEM_228(_) NSL_PP_SEQ_ELEM_227
# define NSL_PP_SEQ_ELEM_229(_) NSL_PP_SEQ_ELEM_228
# define NSL_PP_SEQ_ELEM_230(_) NSL_PP_SEQ_ELEM_229
# define NSL_PP_SEQ_ELEM_231(_) NSL_PP_SEQ_ELEM_230
# define NSL_PP_SEQ_ELEM_232(_) NSL_PP_SEQ_ELEM_231
# define NSL_PP_SEQ_ELEM_233(_) NSL_PP_SEQ_ELEM_232
# define NSL_PP_SEQ_ELEM_234(_) NSL_PP_SEQ_ELEM_233
# define NSL_PP_SEQ_ELEM_235(_) NSL_PP_SEQ_ELEM_234
# define NSL_PP_SEQ_ELEM_236(_) NSL_PP_SEQ_ELEM_235
# define NSL_PP_SEQ_ELEM_237(_) NSL_PP_SEQ_ELEM_236
# define NSL_PP_SEQ_ELEM_238(_) NSL_PP_SEQ_ELEM_237
# define NSL_PP_SEQ_ELEM_239(_) NSL_PP_SEQ_ELEM_238
# define NSL_PP_SEQ_ELEM_240(_) NSL_PP_SEQ_ELEM_239
# define NSL_PP_SEQ_ELEM_241(_) NSL_PP_SEQ_ELEM_240
# define NSL_PP_SEQ_ELEM_242(_) NSL_PP_SEQ_ELEM_241
# define NSL_PP_SEQ_ELEM_243(_) NSL_PP_SEQ_ELEM_242
# define NSL_PP_SEQ_ELEM_244(_) NSL_PP_SEQ_ELEM_243
# define NSL_PP_SEQ_ELEM_245(_) NSL_PP_SEQ_ELEM_244
# define NSL_PP_SEQ_ELEM_246(_) NSL_PP_SEQ_ELEM_245
# define NSL_PP_SEQ_ELEM_247(_) NSL_PP_SEQ_ELEM_246
# define NSL_PP_SEQ_ELEM_248(_) NSL_PP_SEQ_ELEM_247
# define NSL_PP_SEQ_ELEM_249(_) NSL_PP_SEQ_ELEM_248
# define NSL_PP_SEQ_ELEM_250(_) NSL_PP_SEQ_ELEM_249
# define NSL_PP_SEQ_ELEM_251(_) NSL_PP_SEQ_ELEM_250
# define NSL_PP_SEQ_ELEM_252(_) NSL_PP_SEQ_ELEM_251
# define NSL_PP_SEQ_ELEM_253(_) NSL_PP_SEQ_ELEM_252
# define NSL_PP_SEQ_ELEM_254(_) NSL_PP_SEQ_ELEM_253
# define NSL_PP_SEQ_ELEM_255(_) NSL_PP_SEQ_ELEM_254
#
# else
#
# include "nsl/preprocessor/config/limits.h"
#
# if NSL_PP_LIMIT_SEQ == 256
# include "nsl/preprocessor/seq/limits/elem_256.h"
# elif NSL_PP_LIMIT_SEQ == 512
# include "nsl/preprocessor/seq/limits/elem_256.h"
# include "nsl/preprocessor/seq/limits/elem_512.h"
# elif NSL_PP_LIMIT_SEQ == 1024
# include "nsl/preprocessor/seq/limits/elem_256.h"
# include "nsl/preprocessor/seq/limits/elem_512.h"
# include "nsl/preprocessor/seq/limits/elem_1024.h"
# else
# error Incorrect value for the NSL_PP_LIMIT_SEQ limit
# endif
#
# endif
#
# endif
