# /* Copyright (C) 2001
#  * Housemarque Oy
#  * http://www.housemarque.com
#  *
#  * Distributed under the Boost Software License, Version 1.0. (See
#  * accompanying file LICENSE_1_0.txt or copy at
#  * http://www.boost.org/LICENSE_1_0.txt)
#  */
#
# /* Revised by Paul Mensonides (2002) */
#
# /* See http://www.boost.org for most recent version. */
#
# ifndef NSL_PREPROCESSOR_LIST_FOR_EACH_PRODUCT_H
# define NSL_PREPROCESSOR_LIST_FOR_EACH_PRODUCT_H
#
# include "nsl/preprocessor/config/config.h"
# include "nsl/preprocessor/control/if.h"
# include "nsl/preprocessor/facilities/overload.h"
# include "nsl/preprocessor/list/adt.h"
# include "nsl/preprocessor/list/to_tuple.h"
# include "nsl/preprocessor/repetition/for.h"
# include "nsl/preprocessor/tuple/elem.h"
# include "nsl/preprocessor/tuple/to_list.h"
# include "nsl/preprocessor/tuple/rem.h"
# include "nsl/preprocessor/tuple/reverse.h"
# if NSL_PP_VARIADICS_MSVC
# include "nsl/preprocessor/cat.h"
# include "nsl/preprocessor/facilities/empty.h"
# endif
#
# /* NSL_PP_LIST_FOR_EACH_PRODUCT */
#
# define NSL_PP_LIST_FOR_EACH_PRODUCT_OV_2(macro, size, tuple) NSL_PP_LIST_FOR_EACH_PRODUCT_E(NSL_PP_FOR, macro, size, NSL_PP_TUPLE_TO_LIST(size, tuple))
# define NSL_PP_LIST_FOR_EACH_PRODUCT_OV_1(macro, tuple) NSL_PP_LIST_FOR_EACH_PRODUCT_E(NSL_PP_FOR, macro, NSL_PP_TUPLE_SIZE(tuple), NSL_PP_TUPLE_TO_LIST(tuple))
#
# if ~NSL_PP_CONFIG_FLAGS() & NSL_PP_CONFIG_EDG()
#    if NSL_PP_VARIADICS_MSVC
#        define NSL_PP_LIST_FOR_EACH_PRODUCT(macro, ...) NSL_PP_CAT(NSL_PP_OVERLOAD(NSL_PP_LIST_FOR_EACH_PRODUCT_OV_,__VA_ARGS__)(macro,__VA_ARGS__),NSL_PP_EMPTY())
#    else
#        define NSL_PP_LIST_FOR_EACH_PRODUCT(macro, ...) NSL_PP_OVERLOAD(NSL_PP_LIST_FOR_EACH_PRODUCT_OV_,__VA_ARGS__)(macro,__VA_ARGS__)
#    endif
# else
#    define NSL_PP_LIST_FOR_EACH_PRODUCT(macro, ...) NSL_PP_LIST_FOR_EACH_PRODUCT_Q(macro, __VA_ARGS__)
#    define NSL_PP_LIST_FOR_EACH_PRODUCT_Q(macro, ...) NSL_PP_OVERLOAD(NSL_PP_LIST_FOR_EACH_PRODUCT_OV_,__VA_ARGS__)(macro,__VA_ARGS__)
# endif
#
# /* NSL_PP_LIST_FOR_EACH_PRODUCT_R */
#
# define NSL_PP_LIST_FOR_EACH_PRODUCT_R_OV_2(r, macro, size, tuple) NSL_PP_LIST_FOR_EACH_PRODUCT_E(NSL_PP_FOR ## r, macro, size, NSL_PP_TUPLE_TO_LIST(size, tuple))
# define NSL_PP_LIST_FOR_EACH_PRODUCT_R_OV_1(r, macro, tuple) NSL_PP_LIST_FOR_EACH_PRODUCT_E(NSL_PP_FOR ## r, macro, NSL_PP_TUPLE_SIZE(tuple), NSL_PP_TUPLE_TO_LIST(tuple))
#
# if ~NSL_PP_CONFIG_FLAGS() & NSL_PP_CONFIG_EDG()
#    if NSL_PP_VARIADICS_MSVC
#        define NSL_PP_LIST_FOR_EACH_PRODUCT_R(r, macro, ...) NSL_PP_CAT(NSL_PP_OVERLOAD(NSL_PP_LIST_FOR_EACH_PRODUCT_R_OV_,__VA_ARGS__)(r, macro,__VA_ARGS__),NSL_PP_EMPTY())
#    else
#        define NSL_PP_LIST_FOR_EACH_PRODUCT_R(r, macro, ...) NSL_PP_OVERLOAD(NSL_PP_LIST_FOR_EACH_PRODUCT_R_OV_,__VA_ARGS__)(r, macro,__VA_ARGS__)
#    endif
# else
#    define NSL_PP_LIST_FOR_EACH_PRODUCT_R(r, macro, ...) NSL_PP_LIST_FOR_EACH_PRODUCT_R_Q(r, macro, __VA_ARGS__)
#    define NSL_PP_LIST_FOR_EACH_PRODUCT_R_Q(r, macro, ...) NSL_PP_OVERLOAD(NSL_PP_LIST_FOR_EACH_PRODUCT_R_OV_,__VA_ARGS__)(r, macro,__VA_ARGS__)
# endif
#
# if ~NSL_PP_CONFIG_FLAGS() & NSL_PP_CONFIG_EDG()
#    define NSL_PP_LIST_FOR_EACH_PRODUCT_E(impl, macro, size, lists) impl((NSL_PP_LIST_FIRST(lists), NSL_PP_LIST_REST(lists), NSL_PP_NIL, macro, size), NSL_PP_LIST_FOR_EACH_PRODUCT_P, NSL_PP_LIST_FOR_EACH_PRODUCT_O, NSL_PP_LIST_FOR_EACH_PRODUCT_M_0)
# else
#    define NSL_PP_LIST_FOR_EACH_PRODUCT_E(impl, macro, size, lists) NSL_PP_LIST_FOR_EACH_PRODUCT_E_D(impl, macro, size, lists)
#    define NSL_PP_LIST_FOR_EACH_PRODUCT_E_D(impl, macro, size, lists) impl((NSL_PP_LIST_FIRST(lists), NSL_PP_LIST_REST(lists), NSL_PP_NIL, macro, size), NSL_PP_LIST_FOR_EACH_PRODUCT_P, NSL_PP_LIST_FOR_EACH_PRODUCT_O, NSL_PP_LIST_FOR_EACH_PRODUCT_M_0)
# endif
#
# if NSL_PP_CONFIG_FLAGS() & NSL_PP_CONFIG_STRICT()
#    define NSL_PP_LIST_FOR_EACH_PRODUCT_P(r, data) NSL_PP_LIST_FOR_EACH_PRODUCT_P_I data
#    define NSL_PP_LIST_FOR_EACH_PRODUCT_P_I(a, b, res, macro, size) NSL_PP_LIST_IS_CONS(a)
# else
#    define NSL_PP_LIST_FOR_EACH_PRODUCT_P(r, data) NSL_PP_LIST_IS_CONS(NSL_PP_TUPLE_ELEM(5, 0, data))
# endif
#
# if ~NSL_PP_CONFIG_FLAGS() & NSL_PP_CONFIG_MWCC()
#    define NSL_PP_LIST_FOR_EACH_PRODUCT_O(r, data) NSL_PP_LIST_FOR_EACH_PRODUCT_O_I data
#    define NSL_PP_LIST_FOR_EACH_PRODUCT_O_I(a, b, res, macro, size) (NSL_PP_LIST_REST(a), b, res, macro, size)
# else
#    define NSL_PP_LIST_FOR_EACH_PRODUCT_O(r, data) (NSL_PP_LIST_REST(NSL_PP_TUPLE_ELEM(5, 0, data)), NSL_PP_TUPLE_ELEM(5, 1, data), NSL_PP_TUPLE_ELEM(5, 2, data), NSL_PP_TUPLE_ELEM(5, 3, data), NSL_PP_TUPLE_ELEM(5, 4, data))
# endif
#
# if ~NSL_PP_CONFIG_FLAGS() & NSL_PP_CONFIG_EDG()
#    define NSL_PP_LIST_FOR_EACH_PRODUCT_I(r, data) NSL_PP_LIST_FOR_EACH_PRODUCT_I_I(r, NSL_PP_TUPLE_ELEM(5, 0, data), NSL_PP_TUPLE_ELEM(5, 1, data), NSL_PP_TUPLE_ELEM(5, 2, data), NSL_PP_TUPLE_ELEM(5, 3, data), NSL_PP_TUPLE_ELEM(5, 4, data))
# else
#    define NSL_PP_LIST_FOR_EACH_PRODUCT_I(r, data) NSL_PP_LIST_FOR_EACH_PRODUCT_I_D(r, NSL_PP_TUPLE_REM_5 data)
#    define NSL_PP_LIST_FOR_EACH_PRODUCT_I_D(r, data_e) NSL_PP_LIST_FOR_EACH_PRODUCT_I_I(r, data_e)
# endif
#
# define NSL_PP_LIST_FOR_EACH_PRODUCT_I_I(r, a, b, res, macro, size) NSL_PP_LIST_FOR_EACH_PRODUCT_I_II(r, macro, NSL_PP_LIST_TO_TUPLE_R(r, (NSL_PP_LIST_FIRST(a), res)), size)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_I_II(r, macro, args, size) NSL_PP_LIST_FOR_EACH_PRODUCT_I_III(r, macro, args, size)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_I_III(r, macro, args, size) macro(r, NSL_PP_TUPLE_REVERSE(size, args))
#
# define NSL_PP_LIST_FOR_EACH_PRODUCT_C(data, i) NSL_PP_IF(NSL_PP_LIST_IS_CONS(NSL_PP_TUPLE_ELEM(5, 1, data)), NSL_PP_LIST_FOR_EACH_PRODUCT_N_ ## i, NSL_PP_LIST_FOR_EACH_PRODUCT_I)
#
# if ~NSL_PP_CONFIG_FLAGS() & NSL_PP_CONFIG_MWCC()
#    define NSL_PP_LIST_FOR_EACH_PRODUCT_H(data) NSL_PP_LIST_FOR_EACH_PRODUCT_H_I data
# else
#    define NSL_PP_LIST_FOR_EACH_PRODUCT_H(data) NSL_PP_LIST_FOR_EACH_PRODUCT_H_I(NSL_PP_TUPLE_ELEM(5, 0, data), NSL_PP_TUPLE_ELEM(5, 1, data), NSL_PP_TUPLE_ELEM(5, 2, data), NSL_PP_TUPLE_ELEM(5, 3, data), NSL_PP_TUPLE_ELEM(5, 4, data))
# endif
#
# define NSL_PP_LIST_FOR_EACH_PRODUCT_H_I(a, b, res, macro, size) (NSL_PP_LIST_FIRST(b), NSL_PP_LIST_REST(b), (NSL_PP_LIST_FIRST(a), res), macro, size)
#
# define NSL_PP_LIST_FOR_EACH_PRODUCT_M_0(r, data) NSL_PP_LIST_FOR_EACH_PRODUCT_C(data, 0)(r, data)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_M_1(r, data) NSL_PP_LIST_FOR_EACH_PRODUCT_C(data, 1)(r, data)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_M_2(r, data) NSL_PP_LIST_FOR_EACH_PRODUCT_C(data, 2)(r, data)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_M_3(r, data) NSL_PP_LIST_FOR_EACH_PRODUCT_C(data, 3)(r, data)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_M_4(r, data) NSL_PP_LIST_FOR_EACH_PRODUCT_C(data, 4)(r, data)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_M_5(r, data) NSL_PP_LIST_FOR_EACH_PRODUCT_C(data, 5)(r, data)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_M_6(r, data) NSL_PP_LIST_FOR_EACH_PRODUCT_C(data, 6)(r, data)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_M_7(r, data) NSL_PP_LIST_FOR_EACH_PRODUCT_C(data, 7)(r, data)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_M_8(r, data) NSL_PP_LIST_FOR_EACH_PRODUCT_C(data, 8)(r, data)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_M_9(r, data) NSL_PP_LIST_FOR_EACH_PRODUCT_C(data, 9)(r, data)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_M_10(r, data) NSL_PP_LIST_FOR_EACH_PRODUCT_C(data, 10)(r, data)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_M_11(r, data) NSL_PP_LIST_FOR_EACH_PRODUCT_C(data, 11)(r, data)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_M_12(r, data) NSL_PP_LIST_FOR_EACH_PRODUCT_C(data, 12)(r, data)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_M_13(r, data) NSL_PP_LIST_FOR_EACH_PRODUCT_C(data, 13)(r, data)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_M_14(r, data) NSL_PP_LIST_FOR_EACH_PRODUCT_C(data, 14)(r, data)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_M_15(r, data) NSL_PP_LIST_FOR_EACH_PRODUCT_C(data, 15)(r, data)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_M_16(r, data) NSL_PP_LIST_FOR_EACH_PRODUCT_C(data, 16)(r, data)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_M_17(r, data) NSL_PP_LIST_FOR_EACH_PRODUCT_C(data, 17)(r, data)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_M_18(r, data) NSL_PP_LIST_FOR_EACH_PRODUCT_C(data, 18)(r, data)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_M_19(r, data) NSL_PP_LIST_FOR_EACH_PRODUCT_C(data, 19)(r, data)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_M_20(r, data) NSL_PP_LIST_FOR_EACH_PRODUCT_C(data, 20)(r, data)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_M_21(r, data) NSL_PP_LIST_FOR_EACH_PRODUCT_C(data, 21)(r, data)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_M_22(r, data) NSL_PP_LIST_FOR_EACH_PRODUCT_C(data, 22)(r, data)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_M_23(r, data) NSL_PP_LIST_FOR_EACH_PRODUCT_C(data, 23)(r, data)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_M_24(r, data) NSL_PP_LIST_FOR_EACH_PRODUCT_C(data, 24)(r, data)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_M_25(r, data) NSL_PP_LIST_FOR_EACH_PRODUCT_C(data, 25)(r, data)
#
# define NSL_PP_LIST_FOR_EACH_PRODUCT_N_0(r, data) NSL_PP_FOR_ ## r(NSL_PP_LIST_FOR_EACH_PRODUCT_H(data), NSL_PP_LIST_FOR_EACH_PRODUCT_P, NSL_PP_LIST_FOR_EACH_PRODUCT_O, NSL_PP_LIST_FOR_EACH_PRODUCT_M_1)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_N_1(r, data) NSL_PP_FOR_ ## r(NSL_PP_LIST_FOR_EACH_PRODUCT_H(data), NSL_PP_LIST_FOR_EACH_PRODUCT_P, NSL_PP_LIST_FOR_EACH_PRODUCT_O, NSL_PP_LIST_FOR_EACH_PRODUCT_M_2)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_N_2(r, data) NSL_PP_FOR_ ## r(NSL_PP_LIST_FOR_EACH_PRODUCT_H(data), NSL_PP_LIST_FOR_EACH_PRODUCT_P, NSL_PP_LIST_FOR_EACH_PRODUCT_O, NSL_PP_LIST_FOR_EACH_PRODUCT_M_3)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_N_3(r, data) NSL_PP_FOR_ ## r(NSL_PP_LIST_FOR_EACH_PRODUCT_H(data), NSL_PP_LIST_FOR_EACH_PRODUCT_P, NSL_PP_LIST_FOR_EACH_PRODUCT_O, NSL_PP_LIST_FOR_EACH_PRODUCT_M_4)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_N_4(r, data) NSL_PP_FOR_ ## r(NSL_PP_LIST_FOR_EACH_PRODUCT_H(data), NSL_PP_LIST_FOR_EACH_PRODUCT_P, NSL_PP_LIST_FOR_EACH_PRODUCT_O, NSL_PP_LIST_FOR_EACH_PRODUCT_M_5)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_N_5(r, data) NSL_PP_FOR_ ## r(NSL_PP_LIST_FOR_EACH_PRODUCT_H(data), NSL_PP_LIST_FOR_EACH_PRODUCT_P, NSL_PP_LIST_FOR_EACH_PRODUCT_O, NSL_PP_LIST_FOR_EACH_PRODUCT_M_6)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_N_6(r, data) NSL_PP_FOR_ ## r(NSL_PP_LIST_FOR_EACH_PRODUCT_H(data), NSL_PP_LIST_FOR_EACH_PRODUCT_P, NSL_PP_LIST_FOR_EACH_PRODUCT_O, NSL_PP_LIST_FOR_EACH_PRODUCT_M_7)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_N_7(r, data) NSL_PP_FOR_ ## r(NSL_PP_LIST_FOR_EACH_PRODUCT_H(data), NSL_PP_LIST_FOR_EACH_PRODUCT_P, NSL_PP_LIST_FOR_EACH_PRODUCT_O, NSL_PP_LIST_FOR_EACH_PRODUCT_M_8)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_N_8(r, data) NSL_PP_FOR_ ## r(NSL_PP_LIST_FOR_EACH_PRODUCT_H(data), NSL_PP_LIST_FOR_EACH_PRODUCT_P, NSL_PP_LIST_FOR_EACH_PRODUCT_O, NSL_PP_LIST_FOR_EACH_PRODUCT_M_9)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_N_9(r, data) NSL_PP_FOR_ ## r(NSL_PP_LIST_FOR_EACH_PRODUCT_H(data), NSL_PP_LIST_FOR_EACH_PRODUCT_P, NSL_PP_LIST_FOR_EACH_PRODUCT_O, NSL_PP_LIST_FOR_EACH_PRODUCT_M_10)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_N_10(r, data) NSL_PP_FOR_ ## r(NSL_PP_LIST_FOR_EACH_PRODUCT_H(data), NSL_PP_LIST_FOR_EACH_PRODUCT_P, NSL_PP_LIST_FOR_EACH_PRODUCT_O, NSL_PP_LIST_FOR_EACH_PRODUCT_M_11)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_N_11(r, data) NSL_PP_FOR_ ## r(NSL_PP_LIST_FOR_EACH_PRODUCT_H(data), NSL_PP_LIST_FOR_EACH_PRODUCT_P, NSL_PP_LIST_FOR_EACH_PRODUCT_O, NSL_PP_LIST_FOR_EACH_PRODUCT_M_12)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_N_12(r, data) NSL_PP_FOR_ ## r(NSL_PP_LIST_FOR_EACH_PRODUCT_H(data), NSL_PP_LIST_FOR_EACH_PRODUCT_P, NSL_PP_LIST_FOR_EACH_PRODUCT_O, NSL_PP_LIST_FOR_EACH_PRODUCT_M_13)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_N_13(r, data) NSL_PP_FOR_ ## r(NSL_PP_LIST_FOR_EACH_PRODUCT_H(data), NSL_PP_LIST_FOR_EACH_PRODUCT_P, NSL_PP_LIST_FOR_EACH_PRODUCT_O, NSL_PP_LIST_FOR_EACH_PRODUCT_M_14)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_N_14(r, data) NSL_PP_FOR_ ## r(NSL_PP_LIST_FOR_EACH_PRODUCT_H(data), NSL_PP_LIST_FOR_EACH_PRODUCT_P, NSL_PP_LIST_FOR_EACH_PRODUCT_O, NSL_PP_LIST_FOR_EACH_PRODUCT_M_15)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_N_15(r, data) NSL_PP_FOR_ ## r(NSL_PP_LIST_FOR_EACH_PRODUCT_H(data), NSL_PP_LIST_FOR_EACH_PRODUCT_P, NSL_PP_LIST_FOR_EACH_PRODUCT_O, NSL_PP_LIST_FOR_EACH_PRODUCT_M_16)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_N_16(r, data) NSL_PP_FOR_ ## r(NSL_PP_LIST_FOR_EACH_PRODUCT_H(data), NSL_PP_LIST_FOR_EACH_PRODUCT_P, NSL_PP_LIST_FOR_EACH_PRODUCT_O, NSL_PP_LIST_FOR_EACH_PRODUCT_M_17)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_N_17(r, data) NSL_PP_FOR_ ## r(NSL_PP_LIST_FOR_EACH_PRODUCT_H(data), NSL_PP_LIST_FOR_EACH_PRODUCT_P, NSL_PP_LIST_FOR_EACH_PRODUCT_O, NSL_PP_LIST_FOR_EACH_PRODUCT_M_18)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_N_18(r, data) NSL_PP_FOR_ ## r(NSL_PP_LIST_FOR_EACH_PRODUCT_H(data), NSL_PP_LIST_FOR_EACH_PRODUCT_P, NSL_PP_LIST_FOR_EACH_PRODUCT_O, NSL_PP_LIST_FOR_EACH_PRODUCT_M_19)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_N_19(r, data) NSL_PP_FOR_ ## r(NSL_PP_LIST_FOR_EACH_PRODUCT_H(data), NSL_PP_LIST_FOR_EACH_PRODUCT_P, NSL_PP_LIST_FOR_EACH_PRODUCT_O, NSL_PP_LIST_FOR_EACH_PRODUCT_M_20)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_N_20(r, data) NSL_PP_FOR_ ## r(NSL_PP_LIST_FOR_EACH_PRODUCT_H(data), NSL_PP_LIST_FOR_EACH_PRODUCT_P, NSL_PP_LIST_FOR_EACH_PRODUCT_O, NSL_PP_LIST_FOR_EACH_PRODUCT_M_21)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_N_21(r, data) NSL_PP_FOR_ ## r(NSL_PP_LIST_FOR_EACH_PRODUCT_H(data), NSL_PP_LIST_FOR_EACH_PRODUCT_P, NSL_PP_LIST_FOR_EACH_PRODUCT_O, NSL_PP_LIST_FOR_EACH_PRODUCT_M_22)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_N_22(r, data) NSL_PP_FOR_ ## r(NSL_PP_LIST_FOR_EACH_PRODUCT_H(data), NSL_PP_LIST_FOR_EACH_PRODUCT_P, NSL_PP_LIST_FOR_EACH_PRODUCT_O, NSL_PP_LIST_FOR_EACH_PRODUCT_M_23)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_N_23(r, data) NSL_PP_FOR_ ## r(NSL_PP_LIST_FOR_EACH_PRODUCT_H(data), NSL_PP_LIST_FOR_EACH_PRODUCT_P, NSL_PP_LIST_FOR_EACH_PRODUCT_O, NSL_PP_LIST_FOR_EACH_PRODUCT_M_24)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_N_24(r, data) NSL_PP_FOR_ ## r(NSL_PP_LIST_FOR_EACH_PRODUCT_H(data), NSL_PP_LIST_FOR_EACH_PRODUCT_P, NSL_PP_LIST_FOR_EACH_PRODUCT_O, NSL_PP_LIST_FOR_EACH_PRODUCT_M_25)
# define NSL_PP_LIST_FOR_EACH_PRODUCT_N_25(r, data) NSL_PP_FOR_ ## r(NSL_PP_LIST_FOR_EACH_PRODUCT_H(data), NSL_PP_LIST_FOR_EACH_PRODUCT_P, NSL_PP_LIST_FOR_EACH_PRODUCT_O, NSL_PP_LIST_FOR_EACH_PRODUCT_M_26)
#
# endif
